### ISSUE TITLE
Errors when using open SMTP relays

### ISSUE THREAD

**Issue by archen** [mattupstate/flask-mail#112]
Are open SMTP relays not supported in Flask-Mail?

I've looked at #93 and #98 as they seem related, but those issues' resolutions don't fix my problem. I'm using an internal open SMTP relay to send mail, which works fine using vanilla smtplib, but as soon as I try to duplicate the functional send behavior in a Flask-Mail based app (using @tlynn's fork to unmask the actual error), it fails with:

```
send: u'mail FROM:<noreply@mydomain.com> size=287\r\n'
reply: '530 5.7.1 Client was not authenticated\r\n'
reply: retcode (530); Msg: 5.7.1 Client was not authenticated
send: 'rset\r\n'
127.0.0.1 - - [28/May/2015 12:30:21] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/archen/.envs/test_mail/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/archen/.envs/test_mail/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/archen/.envs/test_mail/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/archen/.envs/test_mail/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/archen/.envs/test_mail/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/archen/.envs/test_mail/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/archen/.envs/test_mail/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archen/.envs/test_mail/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archen/flask_mail_test.py", line 26, in index
    mail.send(msg)
  File "/home/archen/.envs/test_mail/src/flask-mail/flask_mail.py", line 507, in send
    message.send(connection)
  File "/home/archen/.envs/test_mail/src/flask-mail/flask_mail.py", line 442, in send
    connection.send(self)
  File "/home/archen/.envs/test_mail/src/flask-mail/flask_mail.py", line 192, in send
    message.rcpt_options)
  File "/usr/lib/python2.7/smtplib.py", line 723, in sendmail
    self.rset()
  File "/usr/lib/python2.7/smtplib.py", line 462, in rset
    return self.docmd("rset")
  File "/usr/lib/python2.7/smtplib.py", line 387, in docmd
    return self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 363, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
SMTPServerDisconnected: Connection unexpectedly closed
```

This is what the simple testing app has in it:
```
from flask import Flask
from flask.ext.mail import Mail, Message

app = Flask(__name__)

app.config.update(
    DEBUG=True,
    # EMAIL SETTINGS
    MAIL_SERVER='smtp.mydomain.com',
    MAIL_PORT=465,
    MAIL_USE_TLS=True,
)

mail = Mail(app)


@app.route("/")
def index():
    msg = Message(
        'Hello',
        sender='noreply@mydomain.com',
        recipients=['me@mydomain.com'])
    msg.body = "This is the email body"
    mail.send(msg)
    return "Sent"


if __name__ == "__main__":
    app.run()
```

**Comment by archen** [comment]
The working code for smtplib is:

```
import smtplib
import sys

if len(sys.argv) != 5:
    print "You must call me like:"
    print "   mailme from to subject msgfile"
    sys.exit()

fromaddr = sys.argv[1]
toaddr = sys.argv[2]
subject = sys.argv[3]
msgfile = sys.argv[4]

try:
    f = open(msgfile)
    msg = f.read()
except:
    print "Invalid Message File: " + msgfile
    sys.exit()

m = "From: %s\r\nTo: %s\r\nSubject: %s\r\nX-Mailer: My-Mail\r\n\r\n" \
    % (fromaddr, toaddr, subject)

smtp = smtplib.SMTP()
smtp.connect('smtp.mydomain.com')
smtp.sendmail(fromaddr, toaddr, m + msg)
smtp.close()
```

called with `python smtplib_test.py noreply@mydomain.com me@mydomain.com test test.msg` where test.msg is a file containing the text `test`

**Comment by archen** [comment]
well, further investigation and tinkering with the code shows that the issue is in starttls/ehlo, not directly related to the send flow. Will update if I get closer to a solution.

**Comment by archen** [comment]
welp... total PEBKAC. notice in my working test I was neither using the same port nor starttls. Changing the code to:

```
smtp = smtplib.SMTP()
smtp.connect('smtp.mydomain.com', '465')
smtp.starttls()
smtp.sendmail(fromaddr, toaddr, m + msg)
smtp.close()
```
nets me the same error. Adjusted my config to match the correct port settings, and everything works as expected.
