### ISSUE TITLE
SMTPServerDisconnected random error

### ISSUE THREAD

**Issue by Garito** [mattupstate/flask-mail#98]
Sometimes it raises, sometimes not!
Hi!
The trace back:
```python
Exception on /projects/issues/tasks/add [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/app/Tasks/__init__.py", line 61, in addTask
    send_mail(title, message, recipients)
  File "/app/TimeFounder/utils.py", line 24, in send_mail
    used.append(recipientTuple)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/lib/python2.7/smtplib.py", line 756, in quit
    res = self.docmd("quit")
  File "/usr/lib/python2.7/smtplib.py", line 386, in docmd
    self.putcmd(cmd, args)
  File "/usr/lib/python2.7/smtplib.py", line 336, in putcmd
    self.send(str)
  File "/usr/lib/python2.7/smtplib.py", line 328, in send
    raise SMTPServerDisconnected('please run connect() first')
SMTPServerDisconnected: please run connect() first
```

The code for this File "/app/TimeFounder/utils.py", line 24, in send_mail:
```python
def send_mail(title, message, recipients):
	if isinstance(message, dict):
		template = env.get_template(message.pop('template'))
		message = template(**message)
	
	used = []
	with mail.connect() as conn:
		for recipient in recipients:
			recipientTuple = (recipient.nick, recipient.email) if 'nick' in recipient else recipient
			
			if recipientTuple not in used:
				used.append(recipientTuple)
				msg = Message(title, sender=(current_app.config['SENDER_NICK'], 
																		 current_app.config['EMAIL_SENDER']),
											recipients=[recipientTuple], body=message)
				conn.send(msg)

	return used
```
Could someone point me what are what I'm missing here?

Thanks a lot

**Comment by Garito** [comment]
Is this package actively developed?

**Comment by mattupstate** [comment]
@Garito Indeed it is. However, I'm quite confused by your problem, `self.host.quit()` should not be executed until the context [exists](https://github.com/mattupstate/flask-mail/blob/master/flask_mail.py#L150-L152). This is tested [here](https://github.com/mattupstate/flask-mail/blob/master/tests.py#L604-L614).

**Comment by Garito** [comment]
Ops, sorry!
This confuses me too since I'm following the examples
Could you recommend me something to try to debug the problem?

Thanks

**Comment by Garito** [comment]
Forget about that!
It turns out that was an exim4 problem

Sorry about that and thanks for your help
